### ISSUE TITLE
Auto-reroute broken

### ISSUE THREAD

**Issue by bear269** [frankthetank7254/feral#17]
Seems to be new servers

**Comment by frankthetank7254** [comment]
what makes you think that? it looks like all the download links are still working

**Comment by bear269** [comment]
I just noticed when i run it only default and cogent give results if you
check the route redirect page you will see there is two new servers named
console.  Im not the greatest code writer but the two ip for these new
routes are missing from your script. Also i was trying to figure out where
the test file is on these two new servers.

Thanks for your contribution

**Comment by bear269** [comment]
Please find them here:

https://console-1.feral.io/test.bin
https://console-2.feral.io/test.bin

You will probably find they're very similar to default or NTT as it's their
upstream.

Regards,
Joshua

**Comment by frankthetank7254** [comment]
I didnt realize there were new routes available! looks like they were just added earlier today. I went ahead and updated the script to use the new routes and test files.

thanks for letting me know!
