### ISSUE TITLE
IPV4 -4

### ISSUE THREAD

**Issue by ne0ark** [frankthetank7254/feral#4]
You should add -4 to Curl when posting to feral web site. It apparently checks for ipv6.

**Comment by frankthetank7254** [comment]
thanks! I used to have an IPv6 check in an old script, and forgot about it for the new one.
As you probably know, the reroute page says it only works with IPv4 addresses.
Im testing "-4"  in curl to see if it will work even when the local machine has IPv6 enabled

**Comment by frankthetank7254** [comment]
it looks like the "-4" option is working well.

thanks!
