### ISSUE TITLE
All routes immediately report 0Mbit/s and nothing changes

### ISSUE THREAD

**Issue by justinforce** [frankthetank7254/feral#7]
This is a new behavior that I noticed recently when I observed that my downloads are all slow again. I run `auto-reroute.sh` in a cron job, so I don't know how long this has been happening. Here's the output I get. The script hangs indefinitely at the end (as does the page https://network.feral.io/reroute when I try to update the route by picking a route and submitting the form) so I hit Ctrl-C to kill it.

```
mike:~% time ./auto-reroute
You are currently using the default route
Testing single segment download speed from Default...
routing through Default results in 0 Mbit/s

Testing single segment download speed from Fiber-Ring#1...
routing through Fiber-Ring#1 results in 0 Mbit/s

Testing single segment download speed from Fiber-Ring#2...
routing through Fiber-Ring#2 results in 0 Mbit/s

Testing single segment download speed from GTT...
routing through GTT results in 0 Mbit/s

Testing single segment download speed from Level3...
routing through Level3 results in 0 Mbit/s

Testing single segment download speed from NTT#1...
routing through NTT#1 results in 0 Mbit/s

Testing single segment download speed from NTT#2...
routing through NTT#2 results in 0 Mbit/s

Routing through Fiber-Ring#2 provided the highest speed of 0 Mbit/s
Setting route to Fiber-Ring#2 / 87.255.32.249 ...
^C
./auto-reroute  0.76s user 0.36s system 9% cpu 11.851 total
```

OS:
```
mike:~% uname -a
Linux mike 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:01 UTC 2015 i686 i686 i686 GNU/Linux
mike:~% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid
```

**Comment by frankthetank7254** [comment]
It looks like the official speed test files are unavailable, and that is why the script is acting this way. From what I can tell, it could be related to some other issues Feral is currently having.
Depending on the version of the script you have, you can check ~./auto-reroute/auto-reroute.log for the log

I will try to update the script to deal with the missing files.

If you do have the log, can you tell me when the issue started?

**Comment by justinforce** [comment]
Thank you for getting back to me, @frankthetank7254! The good news is it's not your script at all. I also emailed Feral's NOC and they said

> This weekend the server handling all of this died and then so did my laptop while I was travelling so all I'm left with is my phone unable to restore things. I'll be back on Tuesday where I will restore the reroute page.
>
> Please open a support ticket and we'll update you as soon as it's back!
>
> Sorry for the trouble caused.

So let's assume nothing's wrong with your script. Thanks!
